-- KTC order workflow hardening.
-- Additive migration: preserves existing order IDs and business data.
create extension if not exists pgcrypto;

alter table public.orders
  add column if not exists tracking_token_hash bytea,
  add column if not exists tracking_token_created_at timestamptz;

create unique index if not exists orders_tracking_token_hash_idx
  on public.orders (tracking_token_hash)
  where tracking_token_hash is not null;

update public.orders
set status = case status
  when 'Confirmed' then 'Order Confirmed'
  when 'Delivered' then 'Delivered & Closed'
  when 'Completed' then 'Delivered & Closed'
  when 'Closed' then 'Delivered & Closed'
  else status
end;

create sequence if not exists public.order_number_seq;

create or replace function public.next_order_number()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := format(
      'ORD-%s-%s',
      extract(year from current_date)::int,
      lpad(nextval('public.order_number_seq')::text, 4, '0')
    );
    exit when not exists (select 1 from public.orders where id = candidate);
  end loop;
  return candidate;
end;
$$;

revoke all on function public.next_order_number() from public, anon;
grant execute on function public.next_order_number() to authenticated;

create table if not exists public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id text not null references public.orders(id) on delete cascade,
  payment_type text not null check (payment_type in ('Advance', 'Balance', 'Other')),
  amount numeric(14,2) not null check (amount >= 0),
  currency text not null default 'USD',
  status text not null default 'Due' check (status in ('Due', 'Received', 'Reconciled', 'Cancelled')),
  bank_reference text,
  payment_date date,
  receipt_document_id uuid,
  notes text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_activity (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  event_type text not null,
  from_value text,
  to_value text,
  metadata jsonb not null default '{}'::jsonb,
  actor_id uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists order_payments_order_id_idx on public.order_payments(order_id);
create index if not exists order_activity_order_id_created_idx on public.order_activity(order_id, created_at desc);

alter table public.order_payments enable row level security;
alter table public.order_activity enable row level security;

drop policy if exists "authenticated manage order payments" on public.order_payments;
create policy "authenticated manage order payments"
on public.order_payments for all to authenticated
using (true) with check (true);

drop policy if exists "authenticated read order activity" on public.order_activity;
create policy "authenticated read order activity"
on public.order_activity for select to authenticated
using (true);

create or replace function public.audit_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status then
    insert into public.order_activity(order_id, event_type, from_value, to_value)
    values (new.id, 'status_changed', old.status, new.status);
  end if;
  return new;
end;
$$;

drop trigger if exists orders_status_audit on public.orders;
create trigger orders_status_audit
after update of status on public.orders
for each row execute function public.audit_order_status_change();

create or replace function public.create_order(
  p_client_id text,
  p_status text default 'Order Confirmed',
  p_incoterm text default 'FOB',
  p_payment_method text default 'LC'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order public.orders;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_status not in (
    'Order Confirmed', 'Advance Payment Received', 'In Production',
    'Ready to Ship', 'Shipped', 'Balance Payment Received', 'Delivered & Closed'
  ) then raise exception 'Invalid order status'; end if;

  insert into public.orders(id, client_id, status, incoterm, payment_method, total_value, production_progress)
  values (public.next_order_number(), p_client_id, p_status, p_incoterm, p_payment_method, 0, 0)
  returning * into new_order;

  insert into public.order_activity(order_id, event_type, to_value)
  values (new_order.id, 'order_created', new_order.status);
  return to_jsonb(new_order);
end;
$$;

revoke all on function public.create_order(text, text, text, text) from public, anon;
grant execute on function public.create_order(text, text, text, text) to authenticated;

create or replace function public.convert_inquiry_to_order(p_inquiry_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  source_inquiry public.inquiries;
  new_order public.orders;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  select * into source_inquiry from public.inquiries where id = p_inquiry_id for update;
  if not found then raise exception 'Inquiry not found'; end if;

  insert into public.orders(
    id, inquiry_id, client_id, incoterm, payment_method, pod_port,
    total_value, status, production_progress
  ) values (
    public.next_order_number(), source_inquiry.id, source_inquiry.client_id,
    source_inquiry.incoterm, source_inquiry.payment_terms, source_inquiry.destination_port,
    source_inquiry.total_value, 'Order Confirmed', 0
  ) returning * into new_order;

  insert into public.order_items(order_id, product_id, product_name, quantity_mt, unit_price, line_total)
  select new_order.id, product_id, product_name, quantity_mt, unit_price, line_total
  from public.inquiry_items where inquiry_id = source_inquiry.id;

  insert into public.order_documents(order_id, document_type, responsible_party, status)
  select new_order.id, document_type, responsible_party, 'Pending'
  from public.document_checklist_templates;

  update public.inquiries set status = 'Accepted' where id = source_inquiry.id;
  insert into public.order_activity(order_id, event_type, to_value, metadata)
  values (new_order.id, 'inquiry_converted', new_order.status, jsonb_build_object('inquiry_id', source_inquiry.id));
  return to_jsonb(new_order);
end;
$$;

revoke all on function public.convert_inquiry_to_order(text) from public, anon;
grant execute on function public.convert_inquiry_to_order(text) to authenticated;

create or replace function public.rotate_buyer_tracking_token(p_order_id text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  raw_token text := encode(extensions.gen_random_bytes(32), 'hex');
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  update public.orders
  set tracking_token_hash = extensions.digest(raw_token, 'sha256'),
      tracking_token_created_at = now()
  where id = p_order_id;
  if not found then raise exception 'Order not found'; end if;
  insert into public.order_activity(order_id, event_type) values (p_order_id, 'tracking_link_rotated');
  return raw_token;
end;
$$;

revoke all on function public.rotate_buyer_tracking_token(text) from public, anon;
grant execute on function public.rotate_buyer_tracking_token(text) to authenticated;

create or replace function public.get_buyer_order_tracking(p_token text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'order_number', o.id,
    'status', case
      when o.status in ('Order Confirmed', 'Advance Payment Received') then 'Confirmed'
      when o.status = 'Balance Payment Received' then 'Shipped'
      when o.status = 'Delivered & Closed' then 'Delivered'
      else o.status
    end,
    'client_name', coalesce(c.company, c.contact, 'Valued Customer'),
    'country', c.country,
    'incoterm', o.incoterm,
    'pol_port', o.pol_port,
    'pod_port', o.pod_port,
    'shipment_deadline', o.shipment_deadline,
    'production_progress', o.production_progress,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'product_name', oi.product_name,
        'quantity_mt', oi.quantity_mt
      ))
      from public.order_items oi where oi.order_id = o.id
    ), '[]'::jsonb),
    'shipment', (
      select jsonb_build_object(
        'shipping_line', s.shipping_line,
        'vessel_voyage', s.vessel_voyage,
        'container_number', s.container_number,
        'bl_number', s.bl_number,
        'etd', s.etd,
        'eta', s.eta,
        'tracking_url', s.tracking_url
      )
      from public.shipments s where s.order_id = o.id
      order by s.created_at desc nulls last limit 1
    )
  )
  from public.orders o
  left join public.clients c on c.id = o.client_id
  where o.tracking_token_hash = extensions.digest(p_token, 'sha256')
  limit 1
$$;

revoke all on function public.get_buyer_order_tracking(text) from public;
grant execute on function public.get_buyer_order_tracking(text) to anon, authenticated;

-- Anonymous buyers use only the restricted RPC above, never raw commercial tables.
revoke select on public.orders, public.clients, public.order_items,
  public.shipments, public.order_documents from anon;

-- Documents remain private. Authenticated staff get object access through RLS.
update storage.buckets set public = false where id = 'order-documents';

drop policy if exists "authenticated read order documents" on storage.objects;
create policy "authenticated read order documents"
on storage.objects for select to authenticated
using (bucket_id = 'order-documents');

drop policy if exists "authenticated upload order documents" on storage.objects;
create policy "authenticated upload order documents"
on storage.objects for insert to authenticated
with check (bucket_id = 'order-documents');

drop policy if exists "authenticated update order documents" on storage.objects;
create policy "authenticated update order documents"
on storage.objects for update to authenticated
using (bucket_id = 'order-documents')
with check (bucket_id = 'order-documents');

drop policy if exists "authenticated delete order documents" on storage.objects;
create policy "authenticated delete order documents"
on storage.objects for delete to authenticated
using (bucket_id = 'order-documents');
